name             'rails-app'
maintainer       'Robert Clark'
maintainer_email 'rbclark@mitre.org'
license          'MIT'
description      'Installs/Configures rails-app'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'application'
depends          'application_ruby'
depends          'apt'
depends          'build-essential'
depends          'nginx'
depends          'nginx_passenger'
depends          'database'
depends          'ssh_known_hosts'